In [ ]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.5) 
# GradientDescentOptimizer 경사하강법

## Sect3. Cost 최소화기법, How to minimize cost

### Ex01. Multi-variable linear regression

In [4]:
from tqdm import tqdm_notebook
import tensorflow as tf

tf.set_random_seed(777)

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1*w1 + x2*w2 + x3*w3 + b
print(hypothesis)

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

Tensor("add_5:0", dtype=float32)


In [8]:
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in tqdm_notebook(range(2001)):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})

    if step % 100 == 0 or step < 10 :
        print("\nStep : {} \nCost : {} \nPrediction :\n{}".format(step, cost_val, hy_val))

           


Step : 0 
Cost : 27199.822265625 
Prediction :
[-4.746768  15.750464   4.27555    5.7535353 16.655096 ]

Step : 1 
Cost : 8558.369140625 
Prediction :
[59.607788 93.09478  80.48686  88.745415 75.64831 ]

Step : 2 
Cost : 2715.2490234375 
Prediction :
[ 95.63871 136.3962  123.15513 135.20978 108.67539]

Step : 3 
Cost : 883.7234497070312 
Prediction :
[115.81229 160.63828 147.04388 161.22372 127.16497]

Step : 4 
Cost : 309.62017822265625 
Prediction :
[127.1079  174.2097  160.41869 175.78822 137.51556]

Step : 5 
Cost : 129.65162658691406 
Prediction :
[133.43309 181.80704 167.9071  183.94263 143.30942]

Step : 6 
Cost : 73.22370910644531 
Prediction :
[136.9755  186.0597  172.09995 188.5082  146.55212]

Step : 7 
Cost : 55.51879119873047 
Prediction :
[138.95995 188.43977 174.44772 191.06458 148.36653]

Step : 8 
Cost : 49.951637268066406 
Prediction :
[140.07216 189.77151 175.76254 192.49606 149.38132]

Step : 9 
Cost : 48.18914031982422 
Prediction :
[140.69601 190.5163  176.49901 

### Ex02. Multi-variable matmul linear regression

In [12]:
import tensorflow as tf

tf.set_random_seed(777)

x_data = [[73., 80., 75.], 
          [93., 88., 93.],
          [89., 91., 90.], 
          [96., 98., 100.], 
          [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate =1e-5)
train = optimizer.minimize(cost)

In [13]:
sess= tf.Session()

sess.run(tf.global_variables_initializer())

for step in tqdm_notebook(range(2001)) :
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train], feed_dict = {X: x_data, Y : y_data})
    
    if step % 100 == 0 or step < 10 :
        print("\nStep : {} \nCost : {} \n Prediction : \n{}".format(
        step,cost_val,hy_val))


Step : 0 
Cost : 14491.9814453125 
 Prediction : 
[[43.877033]
 [56.758087]
 [53.818756]
 [58.703094]
 [44.26979 ]]

Step : 1 
Cost : 4542.75244140625 
 Prediction : 
[[ 90.890015]
 [113.26388 ]
 [109.49504 ]
 [119.33313 ]
 [ 87.36943 ]]

Step : 2 
Cost : 1424.196533203125 
 Prediction : 
[[117.21093]
 [144.89935]
 [140.66617]
 [153.27768]
 [111.49928]]

Step : 3 
Cost : 446.69488525390625 
 Prediction : 
[[131.94711]
 [162.61084]
 [158.11777]
 [172.282  ]
 [125.00865]]

Step : 4 
Cost : 140.30014038085938 
 Prediction : 
[[140.19743]
 [172.52681]
 [167.88829]
 [182.92183]
 [132.57198]]

Step : 5 
Cost : 44.2617073059082 
 Prediction : 
[[144.81656]
 [178.07834]
 [173.35847]
 [188.87866]
 [136.80635]]

Step : 6 
Cost : 14.158638000488281 
 Prediction : 
[[147.4027 ]
 [181.1864 ]
 [176.42105]
 [192.2137 ]
 [139.17697]]

Step : 7 
Cost : 4.7228569984436035 
 Prediction : 
[[148.85066]
 [182.92644]
 [178.1357 ]
 [194.08087]
 [140.50414]]

Step : 8 
Cost : 1.7651798725128174 
 Prediction 

### Ex03. File input linear regression

In [18]:
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('./data/data-01-test-score.csv', delimiter = ',', dtype=np.float32)

In [22]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print("x_data.shape : {}, \tlen(x_data) : {} \nx_data : \n{}".format(x_data.shape, len(x_data), x_data))
print("-"*25)
print("y_data.shape : {}  \ny_data : \n{}".format(y_data.shape, y_data))

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X,W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

x_data.shape : (25, 3), 	len(x_data) : 25 
x_data : 
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
-------------------------
y_data.shape : (25, 1)  
y_data : 
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [23]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(2001) : 
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train], feed_dict = {X : x_data, Y : y_data})
    
    if step % 100 == 0 or step < 10 :
        print("\nStep : {} \nCost : {} \nPrediction :\n{}".format(step, cost_val, hy_val))


Step : 0 
Cost : 30871.0390625 
Prediction :
[[-20.513838  ]
 [ -6.5941644 ]
 [-15.889416  ]
 [-15.902521  ]
 [ -1.764229  ]
 [  2.8374803 ]
 [-14.993187  ]
 [-15.9369335 ]
 [ -0.33107403]
 [  4.3142447 ]
 [-10.500959  ]
 [ -1.8907492 ]
 [-17.482384  ]
 [-15.324179  ]
 [-12.220448  ]
 [ -7.0446    ]
 [-10.685949  ]
 [-21.23749   ]
 [-19.671099  ]
 [-19.334084  ]
 [-15.431911  ]
 [ -6.0225434 ]
 [-16.643566  ]
 [-23.306065  ]
 [-10.287249  ]]

Step : 1 
Cost : 11448.2578125 
Prediction :
[[44.18243 ]
 [71.159454]
 [60.72527 ]
 [67.53627 ]
 [57.53459 ]
 [46.55481 ]
 [47.46454 ]
 [30.366795]
 [72.33347 ]
 [71.61786 ]
 [49.672665]
 [57.439198]
 [61.67152 ]
 [50.47614 ]
 [50.523514]
 [71.85713 ]
 [51.979065]
 [53.718845]
 [55.791725]
 [48.18766 ]
 [57.80907 ]
 [66.9207  ]
 [53.18651 ]
 [41.924053]
 [70.29643 ]]

Step : 2 
Cost : 4267.099609375 
Prediction :
[[ 83.52226 ]
 [118.43691 ]
 [107.31133 ]
 [118.27162 ]
 [ 93.59035 ]
 [ 73.136   ]
 [ 85.44264 ]
 [ 58.52291 ]
 [116.515884]
 [112.54

 [194.21509]]

Step : 1200 
Cost : 29.892072677612305 
Prediction :
[[147.27853]
 [189.70496]
 [180.31886]
 [197.49908]
 [146.84492]
 [111.33551]
 [145.83133]
 [104.9655 ]
 [181.53171]
 [171.6559 ]
 [143.13495]
 [147.11844]
 [185.41992]
 [153.3866 ]
 [148.50952]
 [192.37988]
 [148.66464]
 [172.83456]
 [174.63943]
 [155.0578 ]
 [172.49008]
 [178.20087]
 [163.06107]
 [146.35239]
 [194.12863]]

Step : 1300 
Cost : 28.558568954467773 
Prediction :
[[147.45818]
 [189.56334]
 [180.3647 ]
 [197.53542]
 [146.65926]
 [111.13591]
 [145.93867]
 [105.16774]
 [181.29985]
 [171.37917]
 [143.14574]
 [146.9661 ]
 [185.4746 ]
 [153.42705]
 [148.56248]
 [192.25636]
 [148.6086 ]
 [173.03777]
 [174.74876]
 [155.19188]
 [172.56947]
 [178.07777]
 [163.17091]
 [146.55305]
 [194.04422]]

Step : 1400 
Cost : 27.304662704467773 
Prediction :
[[147.63162 ]
 [189.42595 ]
 [180.40857 ]
 [197.57077 ]
 [146.47873 ]
 [110.943275]
 [146.0438  ]
 [105.36585 ]
 [181.07605 ]
 [171.11354 ]
 [143.15662 ]
 [146.81946 ]
 [18

In [25]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in tqdm_notebook(range(2001)) :
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict = {X : x_data, Y : y_data})
    
    if step % 100 == 0 or step < 10 :
        # print("\nStep : {} \nCost : {} \nPrediction :\n{}".format(step, cost_val, hy_val))
        print("Step : {} \tCost : {} ".format(step, cost_val))

Step : 0 	Cost : 30871.0390625 
Step : 1 	Cost : 11448.2578125 
Step : 2 	Cost : 4267.099609375 
Step : 3 	Cost : 1612.0084228515625 
Step : 4 	Cost : 630.3294677734375 
Step : 5 	Cost : 267.35614013671875 
Step : 6 	Cost : 133.13693237304688 
Step : 7 	Cost : 83.49371337890625 
Step : 8 	Cost : 65.12068939208984 
Step : 9 	Cost : 58.30916976928711 
Step : 100 	Cost : 51.731849670410156 
Step : 200 	Cost : 49.04936981201172 
Step : 300 	Cost : 46.53648376464844 
Step : 400 	Cost : 44.1815299987793 
Step : 500 	Cost : 41.97384262084961 
Step : 600 	Cost : 39.903438568115234 
Step : 700 	Cost : 37.961181640625 
Step : 800 	Cost : 36.13839340209961 
Step : 900 	Cost : 34.42721939086914 
Step : 1000 	Cost : 32.8203010559082 
Step : 1100 	Cost : 31.310731887817383 
Step : 1200 	Cost : 29.892072677612305 
Step : 1300 	Cost : 28.558568954467773 
Step : 1400 	Cost : 27.304662704467773 
Step : 1500 	Cost : 26.125165939331055 
Step : 1600 	Cost : 25.015398025512695 
Step : 1700 	Cost : 23.970928

In [26]:
print("Your score \t: \n", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

Your score 	: 
 [[207.16539]]


In [27]:
print("\nOther scores \t: \n", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))


Other scores 	: 
 [[169.10136]
 [170.76434]]


### Ex04. TF reader linear regression 5

In [1]:
import tensorflow as tf

tf.set_random_seed(777)

filename_queue = tf.train.string_input_producer(
['./data/data-01-test-scort.csv'], shuffle = False, name = 'filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

record_defaults = [[0.],[0.],[0.],[0.]]
xy = tf.decode_csv(value, record_defaults = record_defaults)

train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)


X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

W0911 11:14:16.658407  5588 deprecation.py:323] From <ipython-input-1-3a86c153738d>:6: string_input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
W0911 11:14:16.672038  5588 deprecation.py:323] From C:\Python\Anaconda3\lib\site-packages\tensorflow\python\training\input.py:278: input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
W0911 11:14:16.673033  5588

In [2]:


W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [ ]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

Step_val = []
Cost_val = []

for step in tqdm_notebook(range(2001)):

    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})

    Step_val.append(step)
    Cost_val.append(cost_val)
    
    if step % 100 == 0 or step < 10 :
        print("\nStep : {} \nCost : {} \nPrediction :\n{}".format(step, cost_val, hy_val))

coord.request_stop()
coord.join(threads)

W0911 11:14:20.996477  5588 deprecation.py:323] From <ipython-input-3-888db051c089>:6: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
